global:
  resolve_timeout: 5m

route:
  receiver: telegram-notifications

receivers:
- name: telegram-notifications
  telegram_configs:
  - bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: 8371567382
    send_resolved: true